<html>
<head>
    <title>Gallery Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>All Albums</h1>
<p><a href="/album/edit">Edit Album</a></p>
<?php
if(count($albums) > 0):
    ?>
    <table class="pure-table">
        <tr>
            <th>Title</th>
        </tr>

        <?php
        /**
         * @var \Gallery\Models\AlbumEntity $album
         */
        foreach($albums as $album): ?>

            <tr class="pure-table">
                <td><?php echo $album->getTitle() ?></td>
            </tr>

        <?php endforeach; ?>
    </table>
<?php else: ?>
    <p>No current albums</p>
<?php endif; ?>

</body>
</html>